### ISSUE TITLE
Multipanel Tiff figures from psychonetrics, qgraph(bootnet...

### ISSUE THREAD

**Issue by reetakankaanpaa** [SachaEpskamp/psychonetrics#16]
Hi,

I'm trying to create a multipanel tiff figure (two by two) from bootnet networks I've made. I have those networks saved as tiff-format but how could I multipanel them? 
I've tried par(..) and then plotting, and tiff(...) and then gridExtra::grid.arrange but they don't work. 
I also tried fig1<- qgraph(bootnet...) for four figures without saving them as .tiff, and then opening tiff(...) and then gridExtra::grid.arrange (fig1, fig2, fig3, fig4, ...) but that didn't work either. 

The problem seems to be in the network format. How you/others have created multipanel tiff networks before?

**Comment by SachaEpskamp** [comment]
The output of `qgraph(...)` which is also the output of `plot( network )` with `network <- estimateNetwork(...)` is a base R graphic. For this you can use the `layout` function in R to make a panel. The output from the plot method for the results from bootnet(...)` is a ggplot2 object which works entirely different. I will close this issue here because it isn't related to psychonetrics.
