### ISSUE TITLE
Revisions needed ahead of April release of Matrix 1.7-0 (with R 4.4.0)

### ISSUE THREAD

**Issue by jaganmn** [SachaEpskamp/psychonetrics#28]
The pattern `new("corMatrix", <matrix>, sd=<vector>)` used in (at least) your function `samplestats_norawts` is illegal.  `help("new")` says:

> In the default method, unnamed arguments in the `...` are interpreted as objects from a superclass, and named arguments are interpreted as objects to be assigned into the correspondingly named slots.

But `matrix` is not a superclass of `corMatrix`: `extends("corMatrix", "matrix")` has always been `FALSE`.  Changes in **Matrix** 1.7-0 expose the bug in your function and turn it into an error, hence CRAN will eventually want a patched version of **psychonetrics**.  I recommend specifying all of the slots of the `corMatrix` directly with named arguments.

**Comment by jaganmn** [comment]
Here is a patch replacing calls `as(new("corMatrix", cov2cor(.), sd=diag(.)), "matrix")` with calls `as(as(cov2cor(.), "symmetricMatrix"), "matrix")`, i.e., avoiding `new` altogether: [patch.txt](https://github.com/SachaEpskamp/psychonetrics/files/14667863/patch.txt)

The patched version of **psychonetrics** passes its checks under **Matrix** 1.7-0, at least locally.

**Comment by mmaechler** [comment]
As Matrix 1.7-0 is now on CRAN (only for "R-devel", to become R 4.4.0 in a few weeks),   the problem is now visible as **ERROR**  here  https://cloud.r-project.org/web/checks/check_results_psychonetrics.html  (again "only" for R-devel).

I'd strongly recommend you apply @jaganmn 's patch above  and release a new version of `psychonetrics` replacing the `Depends` line by     `Depends: R (>= 4.4.0)` in your `DESCRIPTION` file, 
*and* in the  `Imports: ` line,  replace `Matrix` by  `Matrix (>= 1.7-0)`.

**Comment by mmaechler** [comment]
Amend:  If you agree that `sd = diag(.)`  was bogous anyway,  I would not even add any `R >= 4.4.0`  or `Matrix >= 1.7-0` requirements...

**Comment by SachaEpskamp** [comment]
Thank you very much for this patch and the information! I am updating the package now. And thanks for catching the weird sd=diag(.) call indeed.
